# Generated by Django 5.1.1 on 2024-10-09 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='accepted', max_length=20),
        ),
    ]
